### ISSUE TITLE
All connections closed when adding a node to the cluster

### ISSUE THREAD

**Issue by dobesv** [jcmoraisjr/haproxy-ingress#116] opened 2018-03-13 19:00 UTC
I'm seeing HAProxy closing all client connections when a node is added to the cluster, but I'm not sure why.  Is there something in the configuration that depends on the number or configuration of nodes?

**Comment by jcmoraisjr** [comment] 2018-03-13 23:41
You mean nodes of the k8s cluster? Any log from HAProxy, from the controller or anything else? Which connections, long lived ones (eg websocket) or all running connections? Any other information?

**Comment by ausmith** [comment] 2018-03-14 12:49
Our usage of haproxy-ingress has not seen this behavior. If @dobesv has steps to reproduce as well as versions used in said testing, I will see if I can reproduce on our own k8s 1.7 infrastructure.

**Comment by dobesv** [comment] 2018-03-14 18:06
![image](https://user-images.githubusercontent.com/327833/37422020-b93db1ec-2777-11e8-817c-b8c2f84774c7.png)

**Comment by dobesv** [comment] 2018-03-14 18:09
If you look at the above graph, it certainly appears that all connections were closed at each transition.

**Comment by dobesv** [comment] 2018-03-14 18:15
Here's an example of what I see in the logs for the last time this happened at 11am:

```
I0314 17:55:06.253874       7 controller.go:320] ingress backend successfully reloaded...
I0314 17:56:41.772689       7 controller.go:311] backend reload required
I0314 17:56:41.773604       7 utils.go:101] haproxy stat socket response: "IP changed from '100.96.16.25' to '100.96.65.82', no need to change the port by 'stats socket command'"
I0314 17:56:41.801376       7 controller.go:165] HAProxy updated through socket, reload not required
I0314 17:56:41.801400       7 controller.go:320] ingress backend successfully reloaded...
I0314 17:58:55.124628       7 controller.go:311] backend reload required
I0314 17:58:55.176655       7 controller.go:165] HAProxy updated through socket, reload not required
I0314 17:58:55.176822       7 controller.go:320] ingress backend successfully reloaded...
I0314 17:58:56.239630       7 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"kube-system", Name:"fluentd-http-ing", UID:"55c7d523-0e04-11e8-b5af-067f282ba1e2", APIVersion:"extensions", ResourceVersion:"12590028", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress kube-system/fluentd-http-ing
I0314 17:58:56.263155       7 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"formative", Name:"meteor", UID:"2b037bca-08ae-11e8-832c-0efa1cd4f60e", APIVersion:"extensions", ResourceVersion:"12590029", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress formative/meteor
I0314 17:58:56.277970       7 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"kube-system", Name:"grafana-ing", UID:"2852685c-08ac-11e8-b5af-067f282ba1e2", APIVersion:"extensions", ResourceVersion:"12590030", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress kube-system/grafana-ing
I0314 17:58:56.291866       7 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"elasticsearch", Name:"kibana-ing", UID:"a986d2fb-11ed-11e8-9c5d-06ae49807f42", APIVersion:"extensions", ResourceVersion:"12590031", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress elasticsearch/kibana-ing
I0314 17:58:56.294553       7 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"formative", Name:"graphql", UID:"2d780046-08ae-11e8-832c-0efa1cd4f60e", APIVersion:"extensions", ResourceVersion:"12590032", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress formative/graphql
I0314 17:58:56.295620       7 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"formative", Name:"graphqlsubs", UID:"329f45e8-08ae-11e8-832c-0efa1cd4f60e", APIVersion:"extensions", ResourceVersion:"12590033", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress formative/graphqlsubs
I0314 17:58:56.309555       7 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"formative", Name:"graphqlmutations", UID:"30118c49-08ae-11e8-832c-0efa1cd4f60e", APIVersion:"extensions", ResourceVersion:"12590034", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress formative/graphqlmutations
I0314 17:58:56.313900       7 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"kube-system", Name:"dashboard-ing", UID:"2c1ff569-08ac-11e8-b5af-067f282ba1e2", APIVersion:"extensions", ResourceVersion:"12590035", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress kube-system/dashboard-ing
I0314 17:58:56.330892       7 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"prometheus", Name:"prometheus-ing", UID:"1e0db3d7-08ac-11e8-b5af-067f282ba1e2", APIVersion:"extensions", ResourceVersion:"12590036", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress prometheus/prometheus-ing
I0314 17:59:14.641487       7 controller.go:311] backend reload required
I0314 17:59:14.753277       7 controller.go:320] ingress backend successfully reloaded...
I0314 18:00:36.612183       7 controller.go:311] backend reload required
I0314 18:00:36.614564       7 utils.go:101] haproxy stat socket response: "IP changed from '127.0.0.1' to '100.96.18.5', port changed from '81' to '3000' by 'stats socket command'"
I0314 18:00:36.705392       7 controller.go:165] HAProxy updated through socket, reload not required
I0314 18:00:36.705422       7 controller.go:320] ingress backend successfully reloaded...
I0314 18:00:36.955978       7 controller.go:311] backend reload required
I0314 18:00:36.958252       7 utils.go:101] haproxy stat socket response: "IP changed from '127.0.0.1' to '100.96.18.7', port changed from '81' to '3000' by 'stats socket command'"
I0314 18:00:36.993980       7 controller.go:165] HAProxy updated through socket, reload not required
I0314 18:00:36.994160       7 controller.go:320] ingress backend successfully reloaded...
I0314 18:00:39.664637       7 controller.go:311] backend reload required
I0314 18:00:39.667866       7 utils.go:101] haproxy stat socket response: "IP changed from '127.0.0.1' to '100.96.18.8', port changed from '81' to '3000' by 'stats socket command'"
I0314 18:00:39.707172       7 controller.go:165] HAProxy updated through socket, reload not required
I0314 18:00:39.707271       7 controller.go:320] ingress backend successfully reloaded...
I0314 18:00:40.636280       7 controller.go:311] backend reload required
I0314 18:00:40.637637       7 utils.go:101] haproxy stat socket response: "IP changed from '127.0.0.1' to '100.96.18.6', port changed from '81' to '3000' by 'stats socket command'"
```

**Comment by dobesv** [comment] 2018-03-14 18:19
I notice that the ingress spec does have a list of the ip addresses of the nodes in it.  I wonder if that list is getting caught up in the structure of things you are comparing:

```
Name:             fluentd-http-ing
Namespace:        kube-system
Address:          34.202.164.50,35.174.173.46,52.205.104.6,54.234.165.81,54.84.10.159,54.85.196.248
Default backend:  default-http-backend:80 (<none>)
TLS:
  tls-keys terminates logger.production.kops.goformative.com
Rules:
  Host                                    Path  Backends
  ----                                    ----  --------
  logger.production.kops.goformative.com  
                                          /   fluentd-http:http-input (100.96.0.2:9880,100.96.1.2:9880,100.96.15.3:9880 + 6 more...)
Annotations:
Events:
  Type    Reason  Age                 From                Message
  ----    ------  ----                ----                -------
  Normal  UPDATE  18m (x29 over 2d)   ingress-controller  Ingress kube-system/fluentd-http-ing
  Normal  UPDATE  18m (x29 over 2d)   ingress-controller  Ingress kube-system/fluentd-http-ing
  Normal  UPDATE  18m (x27 over 2d)   ingress-controller  Ingress kube-system/fluentd-http-ing
  Normal  UPDATE  18m (x24 over 1d)   ingress-controller  Ingress kube-system/fluentd-http-ing
  Normal  UPDATE  18m (x24 over 1d)   ingress-controller  Ingress kube-system/fluentd-http-ing
  Normal  UPDATE  18m (x24 over 1d)   ingress-controller  Ingress kube-system/fluentd-http-ing
  Normal  UPDATE  18m (x24 over 1d)   ingress-controller  Ingress kube-system/fluentd-http-ing
  Normal  UPDATE  18m (x24 over 1d)   ingress-controller  Ingress kube-system/fluentd-http-ing
  Normal  UPDATE  18m (x24 over 1d)   ingress-controller  Ingress kube-system/fluentd-http-ing
  Normal  UPDATE  18m (x24 over 1d)   ingress-controller  Ingress kube-system/fluentd-http-ing
  Normal  UPDATE  18m (x24 over 1d)   ingress-controller  Ingress kube-system/fluentd-http-ing
  Normal  UPDATE  18m (x24 over 1d)   ingress-controller  Ingress kube-system/fluentd-http-ing
  Normal  UPDATE  18m (x24 over 1d)   ingress-controller  Ingress kube-system/fluentd-http-ing
  Normal  UPDATE  18m (x12 over 15h)  ingress-controller  Ingress kube-system/fluentd-http-ing
  Normal  UPDATE  18m (x5 over 7h)    ingress-controller  Ingress kube-system/fluentd-http-ing
  Normal  UPDATE  18m (x3 over 2h)    ingress-controller  Ingress kube-system/fluentd-http-ing
  Normal  CREATE  17m                 ingress-controller  Ingress kube-system/fluentd-http-ing

```


```
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"kubernetes.io/ingress.class":"haproxy"},"name":"dashboard-ing","namespace":"kube-system"},"spec":{"rules":[{"host":"dashboard.production.kops.goformative.com","http":{"paths":[{"backend":{"serviceName":"kubernetes-dashboard","servicePort":80},"path":"/"}]}}],"tls":[{"hosts":["dashboard.production.kops.goformative.com"],"secretName":"tls-keys"}]}}
      kubernetes.io/ingress.class: haproxy
    creationTimestamp: 2018-02-03T06:33:40Z
    generation: 1
    name: dashboard-ing
    namespace: kube-system
    resourceVersion: "12590035"
    selfLink: /apis/extensions/v1beta1/namespaces/kube-system/ingresses/dashboard-ing
    uid: 2c1ff569-08ac-11e8-b5af-067f282ba1e2
  spec:
    rules:
    - host: dashboard.production.kops.goformative.com
      http:
        paths:
        - backend:
            serviceName: kubernetes-dashboard
            servicePort: 80
          path: /
    tls:
    - hosts:
      - dashboard.production.kops.goformative.com
      secretName: tls-keys
  status:
    loadBalancer:
      ingress:
      - ip: 34.202.164.50
      - ip: 35.174.173.46
      - ip: 52.205.104.6
      - ip: 54.234.165.81
      - ip: 54.84.10.159
      - ip: 54.85.196.248
```

**Comment by dobesv** [comment] 2018-03-14 18:20
I notice that the UPDATE and CREATE events on the ingress correspond to the last time when all the connections were dropped.

**Comment by dobesv** [comment] 2018-03-14 18:24
Looking at the structure of the types of config, it seems like the k8s Ingress object is embedded into the config in servers / locations / ingress .  When I look at the type of Ingress, I do see status included in there.

**Comment by dobesv** [comment] 2018-03-14 19:09
It seems like the IP addresses listed correspond to the addresses of the nodes, even though those are not the actual IP addresses that haproxy is accessible from because it is also behind an AWS ELB.

**Comment by dobesv** [comment] 2018-03-14 19:45
I updated the arguments to haproxy-controller to add `--update-status=false` and I think this may have fixed the issue for me.

**Comment by dobesv** [comment] 2018-03-14 19:54
One thing that is interesting about this is that the backend servers don't report a matching in connections.  I wonder if the connections are actually kept open but are no longer reflected in the HAProxy stats?

**Comment by dobesv** [comment] 2018-03-14 20:22
I can confirm that `--update-status=false` get rid of the symptoms I was seeing.

**Comment by dobesv** [comment] 2018-03-14 20:23
I suppose you may want to consider:

1. Default `update-status=false`
2. Ignore changes to ingress status when comparing old and new configuration

I'll leave it up to you whether to close this issue and create new ones or just track it here.

**Comment by jcmoraisjr** [comment] 2018-03-16 01:20
Thank you very much for your time here! Now I understood how to reproduce. I'll have a look at what's happening internally, try some changes and update this same issue.

**Comment by ausmith** [comment] 2018-03-16 17:38
If you are using [`multibinder`](https://github.com/jcmoraisjr/haproxy-ingress#reload-strategy) as the reload strategy, I think this is working as intended as `multibinder` swaps hands the socket file off to the new haproxy process. Are you using the `multibinder` `reload-strategy` in this testing, or `native`?

**Comment by dobesv** [comment] 2018-03-19 04:12
I am using the default, which I believe is native.

**Comment by ausmith** [comment] 2018-03-19 17:57
Agreed, I believe it is the `native` option.

**Comment by jcmoraisjr** [comment] 2018-05-20 23:54
@dobesv there are several improvements on `snapshot` regarding equality of two proxy configurations - using both static or dynamic update. Can you have a look at the current snapshot if it solves this issue? Tks!

**Comment by dobesv** [comment] 2018-05-21 14:46
Hi,

I'll just have to assume it is fixed. I have a workaround in place and I
don't want to mess with it any more.

**Comment by jcmoraisjr** [comment] 2018-05-21 21:17
No problem. I'll close this issue, ping back if you take the time to have a look at this.

**Closed by jcmoraisjr** 2018-05-21 21:17 UTC
Labels: bug
