### ISSUE TITLE
High latency issue after 0.6.*

### ISSUE THREAD

**Issue by guptaarvindk** [jcmoraisjr/haproxy-ingress#267] opened 2018-12-13 22:39 UTC
I am running some HTTPS performance benchmark with HAPROXY ingress controller. Till version 0.6.3-beta, 0.6.4-beta and 0.6.5-beta release, I was able to get decent enough performance:

reqSize=1Kb
connections=50,
latencyAvg=3.56
rps=13950.79

But beyond that when either moving to version 0.6.6-beta or 0.7-snapsot.1 and beyond, I see that latency in my benchmark has increased 3-4 times.

reqSize=1Kb
connections=50,
latencyAvg=10.95
rps=14722.96

I believe changes in this merge might have caused this.  
https://github.com/jcmoraisjr/haproxy-ingress/pull/172/files

Even with latest release I see similar bad performance.  Any idea what changes would have caused this to happen?

**Comment by guptaarvindk** [comment] 2018-12-18 20:52
Thanks for looking into it @jcmoraisjr ,  Earlier my main testing was done on 0.6.3 where I was seeing good performance. After seeing bad performance on 0.7.3, I did a binary search to figure out where performance changed. So based on my quick tests I believe performance difference happened between 0.6.5 and 0.6.6. So I am attaching all three version 0.6.3, 0.6.5 and 0.6.6.

In addition I have seen one more problem with newer version which I have not root caused yet is, I see that if TLS is enabled for some domain, non-tls requests for other domains is not working.  I still have to root cause when it stopped working. But let me know if you have any idea.

[haproxy-0.6.3-beta.cfg.txt](https://github.com/jcmoraisjr/haproxy-ingress/files/2692204/haproxy-0.6.3-beta.cfg.txt)
[haproxy-0.6.5-beta.cfg.txt](https://github.com/jcmoraisjr/haproxy-ingress/files/2692199/haproxy-0.6.5-beta.cfg.txt)
[haproxy-0.6.6-beta.cfg.txt](https://github.com/jcmoraisjr/haproxy-ingress/files/2692205/haproxy-0.6.6-beta.cfg.txt)

Thanks,
-Arvind

**Comment by guptaarvindk** [comment] 2018-12-20 20:05
@jcmoraisjr , feedback I got form HAProxy team is : "Ingress controller configuration is built in a way that each session over SSL is processed 3 times by HAProxy. So don't expect high numbers here." 

May be this could give some clue about what could be causing high latency in newer versions.

**Comment by jcmoraisjr** [comment] 2019-01-01 13:36
Hi. "SSL is processed 3 times" doesn't sound fair. The worst scenario (`nbproc>1`) uses two extra frontends/sockets which only happens on v0.7. If `nbproc=1` or v0.6 is running only one extra socket is used. Both scenarios process SSL just once; the extra frontend is used to inspect SNI on ssl-passthrough config. I do expect high numbers here.

Regarding the performance issue you found: I couldn't see any problem in the diffs of the configurations. I couldn't see anything that could justify the behavior you reported. Perhaps you can share how did you make your tests so I can reproduce this myself.

**Comment by azweb76** [comment] 2019-02-06 21:57
Does the HAProxy team have a suggestion on improving the way SSL is handled? My performance tests between the Nginx and HAProxy ingress controllers show Nginx is faster. I cant believe this.

**Comment by jcmoraisjr** [comment] 2019-02-19 01:38
Hi @azweb76 , the current config builder of haproxy ingress has some latency on large clusters. Such behavior is being fixed on v0.8. Note that nginx is also a great piece of software and will give you a very decent performance, because of that I'd suggest you wait v0.8 beta and run the tests again =)

**Comment by jcmoraisjr** [comment] 2020-10-18 15:42
We're currently in v0.10 GA and a v0.11 which is almost GA as well, and a big amount of work was made on behalf of generate a fast haproxy configuration. I'm very interested in performance benchmarks on every kind of cluster, please provide feedback if you have a scenario where any other controller scales better than HAProxy Ingress - either the controller performance itself on big clusters (5k+ services and/or ingress), or the configured proxy serving requests. Closing this issue since the controller version is rather outdated.

**Closed by jcmoraisjr** 2020-10-18 15:42 UTC
