### ISSUE TITLE
www/non-www redirect missing

### ISSUE THREAD

**Issue by pbabilas** [jcmoraisjr/haproxy-ingress#747] opened 2021-03-03 07:17 UTC
**www/non-www redirect**

I'd like to set automatic global www/non-www (and reverse) redirect by ingress.
Prefer annotation www-redirect and www-redirect-reverse to control which ingress should has that redirect.

Is there any way to get this? or maybe it's already under construction? :)

**Comment by jcmoraisjr** [comment] 2021-03-03 18:00
Currently unsupported but it should be pretty simple add something like "redirect-from" with a comma-separated list of domains from where you want a redirect. Feel free to link other controllers that already implement so we can choose a better approach.

**Comment by jcmoraisjr** [comment] 2021-03-06 02:03
Actually this is a dupe of #715 , closing this on behalf of the other.

**Closed by jcmoraisjr** 2021-03-06 02:03 UTC
Labels: kind/feature, lifecycle/backlog
