### ISSUE TITLE
paths with distinct path types chooses the wrong backend

### ISSUE THREAD

**Issue by JanHolger** [jcmoraisjr/haproxy-ingress#724] opened 2021-01-15 13:03 UTC
**Description of the problem**
cert-manager creates an ingress with the pathType "ImplementationSpecific" which doesn't seem to be supported by haproxy-ingress yet so unless i manually change the pathType to Prefix, the acme challenge will fail. I've never seen this pathType before so i'm not sure if that's a problem with cert-manager but it did work totally fine with nginx-ingress so i guess this is a problem on your side.

**Expected behavior**
Properly handle those ingress objects so cert-manager does work

**Environment information**

HAProxy Ingress version: `v0.11.1`
cert-manager version: `1.1.0`

Ingress objects:

```
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: cm-acme-http-solver-bzgtf
  namespace: example
  labels:
    acme.cert-manager.io/http-domain: '4084921234'
    acme.cert-manager.io/http-token: '1019081234'
    acme.cert-manager.io/http01-solver: 'true'
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: '0.0.0.0/0,::/0'
spec:
  rules:
    - host: example.com
      http:
        paths:
          - path: >-
              /.well-known/acme-challenge/B1xLzUROPkdp1IkQKVyQ5mU2OFhMdxj0K6rRq1Labcd
            pathType: ImplementationSpecific
            backend:
              serviceName: cm-acme-http-solver-69c6s
              servicePort: 8089
```

**Comment by jcmoraisjr** [comment] 2021-01-16 20:43
Hi, HAProxy Ingress supports pathType since v0.11, doc [here](https://haproxy-ingress.github.io/docs/configuration/keys/#path-type). Kubernetes since v1.18 (or so) added pathType field whose default value is `ImplementationSpecific` if not declared. Ingress v1, added in Kubernetes v1.19, has pathType as a mandatory field.

I couldn't reproduce the issue, either using `ImplementationSpecific` or `Prefix` pathTypes. I created this same ingress resource with this same path in front an echoserver, curl it just like Let's Encrypt would do and haproxy sent the request to my backend.

Maybe you have other configurations around which broke this one. Please share with us if you create a minimal deployment that reproduces this issue, so with a reproducer we can provide a proper fix.

**Comment by JanHolger** [comment] 2021-01-17 21:21
I have this issue on 2 independent kubernetes 1.19 clusters managed by rancher. I'm using MetalLB in layer 2 mode and set up haproxy-ingress using the helm chart like described in the wiki but with a static loadBalancerIP instead of host networking. I've installed cert-manager using their installation instructions and created a ClusterIssuer for letsencrypt production.

Then i've created the following ingress:
```
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: docs
  namespace: javawebstack
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
    - hosts:
        - javawebstack.org
      secretName: docs
  rules:
    - host: javawebstack.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: docs
                port:
                  number: 80
```
cert-manager then created the ingress i've already provided in the issue description but haproxy-ingress still matches my own instead of the cert-manager ingress. As soon as i change the pathType of the cert-manager ingress to Prefix it's getting matched and the challenge works. So either the pathType or the order in which the ingresses are created / updated seem to have an impact on the order and priority in which the ingresses are getting matched.

Both clusters are unfortunately already running some production stuff so i can't give you direct access. Just tell me if you need any more information or if I should try something out.

**Comment by jcmoraisjr** [comment] 2021-01-17 22:04
Thanks for the detailed description. Please change the pathType of your ingress to `ImplementationSpecific` just to confirm if this will fix the problem. The behavior will be pretty much the same for the root path, doc [here](https://haproxy-ingress.github.io/docs/configuration/keys/#path-type).

The problem here is that the current implementation does the matches per path type, being `Prefix` with higher precedence than `ImplementationSpecific`. Since the acme server request matches your ingress, it'll be used instead due to this precedence. You can work around it avoiding mix of path types which overlaps each other until a proper fix is implemented.

**Comment by mogoman** [comment] 2021-01-28 19:53
@JanHolger I have been struggling with this for days until I stumbled on this issues -  .well-known urls were not being matched by the controller to the acme pod. I can confirm: changing path type to Prefix fixed the problem for me too. Until Kubernetes 1.19 this has never been an issue for me, in prod I've issued dozens certificates in the past 2 years and the only thing that changed recently was the k8 upgrade.

**Comment by jcmoraisjr** [comment] 2021-02-02 11:42
Hey there, v0.12-beta.2 was just released and should fix this one. Please give us some feedback if you can test using v0.12 branch. Planning to tag v0.11 tomorrow with this same fix, but it'd be great if you can confirm that everything is working as expected before we issue a new v0.11.

**Comment by mogoman** [comment] 2021-02-02 15:01
Hi. Created a new request on v0.11 and the ingress incorrectly routed the .well-known path (as per the text above just to ensure I am reproducing the problem). I upgraded to v0.12-beta.2 and the cert got issued before I could even check the ingress, so from my side the fix appears to be working.

**Comment by jcmoraisjr** [comment] 2021-02-03 10:57
`v0.12-beta.2`, and also `v0.11.2` tagged a few minutes ago have the fix, please update here if you still have any problem. Closing.

Thanks @mogoman for the test and the quick response!

**Closed by jcmoraisjr** 2021-02-03 10:57 UTC
Labels: kind/bug, lifecycle/backlog
