### ISSUE TITLE
Liveness probe failes for v0.9, v0.9.1, response times are growing unbounded 

### ISSUE THREAD

**Issue by antonmatsiuk** [jcmoraisjr/haproxy-ingress#650] opened 2020-08-26 13:58 UTC
After upgrading to 0.9.1 from 0.8.5 haproxy-ingress restarts constantly (every minute) under moderate load with following message:
```
Liveness probe failed: Get http://{{ INTERNAL_IP }}:10253/healthz: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```
Increasing `initialDelaySeconds` and `timeoutSeconds ` for `livenessProbe` solves this issue for some time but then responce times of `/healthz` endpoint start growing again resulting in haproxy restarts, additionally all other endpoints slow down unbounded as well. The resource consumption of the Pod doesn't increase and does not hit the limit boundaries ( < 50 % of RAM and CPU limits).

HTTP/2 is disabled via configmap.
```
tls-alpn: "http/1.1"
use-htx: "false"
```
No errors and nothing suspicious in the container log.

**Comment by jcmoraisjr** [comment] 2020-08-26 17:52
Hi, it seems to me that you're facing a haproxy issue. Perhaps your workload is making haproxy spin and waste cpu. Please confirm if you can reproduce this in v0.10 (beta but rock solid, using it in prod since ages). v0.10 has also metrics, I'd suggest you to configure it, doc [here](https://haproxy-ingress.github.io/docs/examples/metrics/), and follow eg proc use versus rps/conns increase during your uptime. You can also test with htx even if you don't use h2.

**Comment by antonmatsiuk** [comment] 2020-08-27 08:12
@jcmoraisjr thank you for the feedback. CPU/Memory consumption for the Pod stays normal and do not increase significantly with rps/conns growth staying below 30% of k8s pod limits. We monitor them with kube-prometheus. I'll try v0.10 and will give a feedback.

**Comment by antonmatsiuk** [comment] 2020-08-27 10:40
@jcmoraisjr figured out the issue. Our HAProxy started to hit default max-connections=2000 limit, silently dropping new connections without any warnings in logs. For v0.9.1 and v0.10-beta.3 the LivenessProbes were also dropped resulting in restarts of  HaProxy, for v0.8.5 livenessProbes were not counted (?) against max-connections keeping the LB up and running but dropping production clients. Only digging deeper into the haproxy-exporter metrics helped to reveal the issue. It's really bad that HaProxy doesn't write any warnings in logs that `max-connections` limit was reached.

**Comment by jcmoraisjr** [comment] 2020-10-18 19:18
Good to know it's now acknowledged and fixed. Closing.

Regarding the log of maxconn reached - on the other hand haproxy gives us lots of metrics which helps to understand what's happening internally and this is greatly exposed by the HAProxy Ingress dashboard.

**Closed by jcmoraisjr** 2020-10-18 19:18 UTC
