### ISSUE TITLE
haproxy-ingress locks up attempting leader election

### ISSUE THREAD

**Issue by zapman449** [jcmoraisjr/haproxy-ingress#47] opened 2017-09-12 17:35 UTC
```
E0912 17:17:48.511187       6 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "ingress-controller-leader-haproxy": the object has been modified; please apply your changes to the latest version and try again
```

haproxy-ingress version haproxy-ingress:v0.4-snapshot.4
Kubernetes version 1.5.5

Works great, other than this lock up.  After that happens, no new changes in the cluster get registered.

**Comment by jcmoraisjr** [comment] 2017-09-12 21:39
Couldn't reproduce this (yet). How many instances do you have running at the same time? Any other detail of your deployment which worth to mention?

**Comment by zapman449** [comment] 2017-09-13 00:33
2 worker nodes, 3 masters built by kops.

It MIGHT have been triggered by a lurking nginx-ingress we had (thought we) deleted.  We haven't replicated it since actually deleting it.  If it survives the night, I think we can close the ticket.

**Comment by Scukerman** [comment] 2017-09-13 09:42
I have the same messages in log only if I run controller as a DaemonSet.

**Comment by zapman449** [comment] 2017-09-13 12:12
we are running as a daemonset...

**Comment by zapman449** [comment] 2017-09-13 12:14
And we locked up overnight

**Comment by Scukerman** [comment] 2017-09-13 12:33
https://github.com/kubernetes/ingress/issues/1297

**Comment by zapman449** [comment] 2017-09-13 12:41
@Scukerman Dumb question: What is the relationship between kubernetes/ingress/haproxy and jcmoraisjr/haproxy-ingress?

**Comment by Scukerman** [comment] 2017-09-13 13:28
It is the same project. Check the README.md and you'll see that some of the links point to the Ingress repo docs.

**Comment by mbreitung** [comment] 2017-09-19 23:25
I can confirm that https://github.com/kubernetes/ingress/pull/1338 fixes this issue.

**Comment by jcmoraisjr** [comment] 2017-09-27 20:31
Sorry the long delay, vacation here.

@zapman449 b66c7f9 should fix this. I'll provide a new image in the following days. Let us know if you still have any problem.

@Scukerman and @mbreitung thanks for sharing your findings, this way fix HAProxy Ingress is a lot easier.

**Comment by jcmoraisjr** [comment] 2017-10-01 17:11
@zapman449 please report back - commenting and/or closing the issue - if the problem persists. Fyi the canary tag was just updated with this fix.

**Comment by zapman449** [comment] 2017-10-02 12:04
Building from master allowed us to move past this problem.  Thank you.

**Comment by zapman449** [comment] 2017-10-02 13:35
Out of curiosity, when will a snapshot release be forthcoming?

**Comment by Scukerman** [comment] 2017-10-02 13:39
@zapman449 `docker pull quay.io/jcmoraisjr/haproxy-ingress:v0.4-beta.1`
Doesn't it work yet?

**Comment by zapman449** [comment] 2017-10-02 20:47
It does.  I missed the shift from snapshot to beta

**Closed** 2017-10-03 01:12 UTC
Labels: bug
