### ISSUE TITLE
HAProxy backend is marked as DOWN even though cfg has working Pods listed as servers

### ISSUE THREAD

**Issue by mkubaczyk** [jcmoraisjr/haproxy-ingress#807] opened 2021-06-23 12:17 UTC
**Description of the problem**

HAProxy is reporting specific backend to be DOWN even though two servers are listed in the configuration file for that backend. I confirmed these two servers were pointing at existing, working Pods of a service.

Having a chance while this happened for us, I quickly run stats on port 1936 and found out that:

<img width="1670" alt="Screenshot 2021-06-23 at 11 38 22" src="https://user-images.githubusercontent.com/12384536/123092451-c4c6a600-d42a-11eb-92a7-d368f8f73f27.png">

even though at the same time HAProxy had a configuration of:

```/etc/haproxy # cat haproxy5-backend324.cfg 
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# #
# #   HAProxy Ingress Controller
# #   --------------------------
# #   This file is automatically updated, do not edit
# #
#
backend connect_audit-report_6280
    mode http
    balance leastconn
    timeout queue 10s
    timeout server 300s
    http-request set-header X-Original-Forwarded-For %[hdr(x-forwarded-for)] if { hdr(x-forwarded-for) -m found }
    http-request del-header x-forwarded-for
    option forwardfor
    server srv007 10.147.65.36:6280 weight 1 check inter 2s
    server srv008 10.147.65.94:6280 weight 1 check inter 2s
    server srv003 127.0.0.1:1023 disabled weight 1 check inter 2s
    server srv004 127.0.0.1:1023 disabled weight 1 check inter 2s
    server srv006 127.0.0.1:1023 disabled weight 1 check inter 2s
    server srv005 127.0.0.1:1023 disabled weight 1 check inter 2s
    server srv002 127.0.0.1:1023 disabled weight 1 check inter 2s
    server srv001 127.0.0.1:1023 disabled weight 1 check inter 2s
```
This means srv007 and srv008 is pointing at working Pods but HAProxy does not see them according to stats output above.

It actually lasted for some time according to prometheus metric:

![Untitled](https://user-images.githubusercontent.com/12384536/123093437-fbe98700-d42b-11eb-945b-e2962f4b091b.png)

and only after manual forced restart of one Pod of our service it caused HAProxy to change its location in config to srv003 and hence treat it like UP:

<img width="1670" alt="Screenshot 2021-06-23 at 11 47 10" src="https://user-images.githubusercontent.com/12384536/123093501-13287480-d42c-11eb-81c0-c2829aa1a373.png">

**Expected behavior**

An expected behaviour is for the HAproxy to always represent the state of the cfg file for a backend.

**Steps to reproduce the problem**

I cannot propose anything to reproduce this. We've encountered this few times before but this was the only case we had it ongoing so I had a chance to take some screenshots etc.

**Environment information**

HAProxy Ingress version: `v0.12.2`

Command-line options:

```
    Args:
      --configmap=core/haproxy-ingress-stack-controller-internal
      --ingress-class=haproxy-internal
      --controller-class=internal
      --backend-shards=1000
      –-sort-endpoints-by=endpoint
      --default-backend-service=core/haproxy-ingress-stack-default-backend
      --wait-before-shutdown=310
```

Global options:

```
data:
  config-defaults: |
    option clitcpka
  config-global: |
    tune.ssl.cachesize 1000000
  drain-support: "true"
  healthz-port: "10253"
  hsts: "false"
  max-connections: "10000"
  prometheus-port: "9101"
  ssl-options: ssl-min-ver TLSv1.2
  ssl-redirect: "false"
  stats-port: "1936"
  syslog-endpoint: 127.0.0.1:514
  timeout-client: 20000s
  timeout-client-fin: 1s
  timeout-connect: 5s
  timeout-http-request: 5s
  timeout-keep-alive: 5s
  timeout-queue: 5s
  timeout-server: 30s
  timeout-server-fin: 1s
  timeout-tunnel: 1m
  use-proxy-protocol: "false"
```

Ingress objects:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/balance-algorithm: leastconn
    ingress.kubernetes.io/proxy-body-size: unlimited
    ingress.kubernetes.io/timeout-client: 300s
    ingress.kubernetes.io/timeout-queue: 10s
    ingress.kubernetes.io/timeout-server: 300s
  labels:
    [...]
  name: audit-report
spec:
  ingressClassName: haproxy-internal
  rules:
  - host: <some domain>
    http:
      paths:
      - backend:
          service:
            name: audit-report
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
```

**Comment by jcmoraisjr** [comment] 2021-06-23 13:35
Thank you so much for the detailed description. Do you see anything useful from the logs? The most interesting logs are related with error to dynamically update the haproxy state. I'd also suggest you to add `--v=2` in the command-line options, it adds just a few verbosity but useful on this use case.

**Comment by mkubaczyk** [comment] 2021-06-23 13:51
Unfortunately nothing useful on logs. Nothing to provide that's worth anything in this particular case.
 
I'll deploy the controller with `--v=2` everywhere so if something occurs again it will be already there, but I don't know when this will eventually happen. :-)

**Comment by jcmoraisjr** [comment] 2021-06-26 19:55
Still investigating this issue. It's (almost) clear to me that a prior event (may be a bug or a broken haproxy config) leave the model with 8 servers (reflected in the cfg file) and haproxy with 6 (reflected in the stats). A few reconciliations after that event, which didn't start a reload, tried to use a server slot that the controller thinks that's available in haproxy but it isn't.

I revisited a couple of times the code that checks if a reload is needed and I cannot see a problem. However some dynamic update responses aren't properly evaluated and, depending on the response, may lead to differences between what the controller knows about haproxy and how it is really configured.

So the plan here is to properly parse haproxy response when changing a server slot - a reload will be enforced if it responds with anything different from the known and expected responses. This should never happen but your evidences prove me wrong, and after all haproxy is in fact the source of truth so let's use it in our favor. Implementing the response parsing will prevent us from leaving haproxy with an old state due to a bug or so and will help in the use case you described.

Another improvement is to help the sysadmin to identify that a reload failed in the last attempt, because this is known to generate inconsistencies between the model and that old haproxy with an old state. I'll add a log on every reconciliation which leads to dynamic update if the last reload failed.

One more question, just to check if I can take a step forward - can you confirm in the logs if you can see any `error reloading server` between the last successful reload and the outage? Reloads will always end up with a `haproxy successfully reloaded` or a `error reloading server` being the later a sign that something is inconsistent. Any other info that you judge useful based on the findings I've described will be very much appreciated as well.

**Comment by mkubaczyk** [comment] 2021-06-28 08:07
There were no lines like `error reloading server` or `haproxy successfully reloaded`, just few of `haproxy updated without needing to reload` when I searched for `reload` string in logs around that time. Nothing else worth being mentioned in this thread unfortunately.
As I said before, I increased the verbosity of logs everywhere on the controller so whenever this happens again on either QA or PROD environment, we'll have some more things to go through. :-)

**Comment by jcmoraisjr** [comment] 2021-07-11 20:55
`v0.12.6` now will enforce a reload if for any reason a server cannot be found, even if the in-memory model think it should be there. This will ensure that data will always be synchronized. Closing, and please share any suspicious log, or logs emitted during any suspicious behavior you may find. Closing.

**Closed by jcmoraisjr** 2021-07-11 20:55 UTC
Labels: kind/bug

**Comment by jcmoraisjr** [comment] 2021-08-08 01:00
A followup info, maybe I found the root cause of this issue, the whole saga is described in #835 . I'll notify here as soon as we have a new tag in the next few days.

**Comment by jcmoraisjr** [comment] 2021-08-11 00:35
`v0.12.7` was just released and should fix the root cause of this issue.
