### ISSUE TITLE
server/cookie names when dynamic scaling is off

### ISSUE THREAD

**Issue by brianloss** [jcmoraisjr/haproxy-ingress#502] opened 2020-01-16 15:08 UTC
I finally got around to checking out v0.8, and I noticed that when dynamic scaling is off, the server name is still a name such as "srv001". In prior versions, the server name was the pod name. It is critical for my use case that the server name be the pod name (really it's the cookie name that's critical, but having the server name match helps with monitoring/debugging). We rely on this in order to provide direct access to servers for testing and debugging issues.

Is there any way to make this behave like it did before so that when dynamic scaling is off (and ingress.kubernetes.io/session-cookie-dynamic is set to false), the generated server and cookie name match the pod name?

**Comment by jcmoraisjr** [comment] 2020-01-17 00:48
Hi, this was slightly discussed on #469 . I'm finishing some metric docs right now and I'll have the time to new improvements shortly - this has some priority to me since it's a small regression.

**Comment by brianloss** [comment] 2020-01-17 12:36
That would be great, thanks! Sorry about the duplicate ticket.

**Comment by jcmoraisjr** [comment] 2020-01-24 01:49
Please have a look at #507 and say how it sounds. I'm fine to patch up to v0.8 since it's a regression and doesn't touch any internals.

**Comment by brianloss** [comment] 2020-01-26 14:48
Sorry for the delayed response—I’ve been out on holiday. This looks good, and would be very useful to us to have in v0.8. Thanks!

**Comment by jcmoraisjr** [comment] 2020-02-07 11:04
Hi, added `backend-server-naming` which can be used globally or per ingress object as an annotation. Merged up to v0.8.1. Docs [here](https://haproxy-ingress.github.io/docs/configuration/keys/#backend-server-naming). Closing, let me know if you have any problem.

**Closed by jcmoraisjr** 2020-02-07 11:04 UTC
