### ISSUE TITLE
haproxy-ingress pod status CrashLoopBackOff

### ISSUE THREAD

**Issue by GarrettGeorge** [jcmoraisjr/haproxy-ingress#276] opened 2019-01-03 22:44 UTC
When I do `kubectl get pod` I see the status of my `haproxy-ingress` has a status of `CrashLoopBackOff`. Also when I do `kubectl get ingress` there's no address listed. 

For reference I'm using the guide described [here](https://www.haproxy.com/blog/haproxy_ingress_controller_for_kubernetes/)

My k8s cluster is being managed by Rancher on a single node VM (for testing) with two network adapters in order to have separate IPs for `rancher-server` and `rancher-agent`.

**Comment by gjtempleton** [comment] 2019-01-04 10:14
What do you see when you describe the pod and run `kubectl logs` against the pod?

**Comment by GarrettGeorge** [comment] 2019-01-04 16:00
`$ kubectl describe pod haproxy-ingress-687fbff66-bjzdp` gives this:

```
Name:               haproxy-ingress-687fbff66-bjzdp
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:              [node_name]/[node_ip]
Start Time:         Thu, 03 Jan 2019 16:26:30 -0600
Labels:             pod-template-hash=243969922
                    run=haproxy-ingress
Annotations:        cni.projectcalico.org/podIP: 10.42.0.19/32
Status:             Running
IP:                 xx.xx.xx.xx
Controlled By:      ReplicaSet/haproxy-ingress-687fbff66
Containers:
  haproxy-ingress:
    Container ID:  docker://3a571d8edf87f2a1b0218c2e12438d728cf3b16ae23e4b6e1cc5a724991fbcdd
    Image:         quay.io/jcmoraisjr/haproxy-ingress
    Image ID:      docker-pullable://quay.io/jcmoraisjr/haproxy-ingress@sha256:83d61797257785ab49dc6480f785fca59758204090909d79e5ee54c14966b835
    Ports:         80/TCP, 8443/TCP, 1936/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP
    Args:
      --default-backend-service=default/ingress-default-backend
      --default-ssl-certificate=default/tls-secret
      --configmap=$(POD_NAMESPACE)/haproxy-configmap
      --reload-strategy=native
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Fri, 04 Jan 2019 09:55:36 -0600
      Finished:     Fri, 04 Jan 2019 09:55:36 -0600
    Ready:          False
    Restart Count:  209
    Environment:
      POD_NAME:       haproxy-ingress-687fbff66-bjzdp (v1:metadata.name)
      POD_NAMESPACE:  default (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-cxlpk (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  default-token-x:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  [x]
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason   Age                   From                      Message
  ----     ------   ----                  ----                      -------
  Warning  BackOff  36s (x4721 over 17h)  kubelet, jsfitdrancher01  Back-off restarting failed container
```

and then running `$ kubectl logs haproxy-ingress-687fbf66-bjzdp`

```
I0104 15:55:36.332195       6 launch.go:141]
Name:       HAProxy
Release:    v0.6
Build:      git-54e261a
Repository: https://github.com/jcmoraisjr/haproxy-ingress
I0104 15:55:36.332305       6 launch.go:144] Watching for ingress class: haproxy
I0104 15:55:36.332669       6 launch.go:344] Creating API client for https://10.43.0.1:443
I0104 15:55:36.345378       6 launch.go:356] Running in Kubernetes Cluster version v1.11 (v1.11.5) - git (clean) commit 753b2dbc622f5cc417845f0ff8a77f539a4213ea - platform linux/amd64
F0104 15:55:36.346334       6 launch.go:164] ✖ It seems the cluster it is running with Authorization enabled (like RBAC) and there is no permissions for the ingress controller. Please check the configuration
```

**Comment by jcmoraisjr** [comment] 2019-01-06 12:09
Hi, how did you deploy HAProxy Ingress? Perhaps you're missing rbac config, see [here](https://github.com/jcmoraisjr/haproxy-ingress/tree/master/examples/rbac) how it works and how to configure permission to the cluster.

**Comment by rendiok** [comment] 2019-01-16 09:39
Hi,

We have a similar situation with some differences.  Following the main [guide](https://github.com/jcmoraisjr/haproxy-ingress/blob/master/examples/setup-cluster.md#five-minutes-deployment) , we are deploying the daemonset on our 3 bare-metal nodes and after some seconds we received a CrashLoopBackOff.

The logs are showing this:

```
I0116 08:54:02.176030       7 launch.go:141] 
Name:       HAProxy
Release:    v0.6.1
Build:      git-54e261a
Repository: https://github.com/jcmoraisjr/haproxy-ingress
I0116 08:54:02.176579       7 launch.go:144] Watching for ingress class: haproxy
I0116 08:54:02.177203       7 launch.go:344] Creating API client for https://10.3.0.1:443
I0116 08:54:20.269354       7 main.go:45] Shutting down with signal terminated
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x45d002]

goroutine 12 [running]:
github.com/jcmoraisjr/haproxy-ingress/pkg/controller.(*HAProxyController).Stop(0xc420259f80, 0x1c, 0xc420029790)
        /home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/controller/controller.go:80 +0x48
main.handleSignal(0xc420259f80, 0xc42005ea20)
        /home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/main.go:46 +0x163
created by main.main
        /home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/main.go:30 +0x88
```

Describe pod
```
Name:           haproxy-ingress-b948b
Namespace:      ingress-controller
Node:           node2.*****.biz/217.XX.XX.XX
Start Time:     Wed, 16 Jan 2019 09:29:35 +0100
Labels:         controller-revision-hash=119096995
                pod-template-generation=1
                run=haproxy-ingress
Annotations:    <none>
Status:         Running
IP:             217.XX.XX.XX
Controlled By:  DaemonSet/haproxy-ingress
Containers:
  haproxy-ingress:
    Container ID:  docker://f6ff586e84f2e0a332f71dbc80793b6fd51c375ede675f5f905a793ce8fa455b
    Image:         quay.io/jcmoraisjr/haproxy-ingress
    Image ID:      docker-pullable://quay.io/jcmoraisjr/haproxy-ingress@sha256:84fefc3776813834f86a73c2e139ed37aadc4cfd52d26566ca3efa345bc36565
    Ports:         80/TCP, 443/TCP, 1936/TCP
    Host Ports:    80/TCP, 443/TCP, 1936/TCP
    Args:
      --default-backend-service=$(POD_NAMESPACE)/ingress-default-backend
      --configmap=$(POD_NAMESPACE)/haproxy-ingress
      --sort-backends
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Wed, 16 Jan 2019 09:54:02 +0100
      Finished:     Wed, 16 Jan 2019 09:54:20 +0100
    Ready:          False
    Restart Count:  13
    Liveness:       http-get http://:10253/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      POD_NAME:       haproxy-ingress-b948b (v1:metadata.name)
      POD_NAMESPACE:  ingress-controller (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from ingress-controller-token-2t8lx (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  ingress-controller-token-2t8lx:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ingress-controller-token-2t8lx
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/unreachable:NoExecute
Events:
  Type     Reason                 Age                    From                                         Message
  ----     ------                 ----                   ----                                         -------
  Normal   SuccessfulMountVolume  27m                    kubelet, node2.*****.biz  
MountVolume.SetUp succeeded for volume "ingress-controller-token-2t8lx"
  Normal   Created                27m (x3 over 27m)      kubelet,node2.*****.biz
  Created container
  Normal   Started                27m (x3 over 27m)      kubelet, node2.*****.biz
  Started container
  Warning  Unhealthy              26m (x7 over 27m)      kubelet, node2.*****.biz
  Liveness probe failed: Get http://217.182.93.196:10253/healthz: dial tcp 217.XX.XX.XX:10253: getsockopt: connection refused
  Normal   Pulling                26m (x4 over 27m)      kubelet, node2.*****.biz
  pulling image "quay.io/jcmoraisjr/haproxy-ingress"
  Normal   Killing                26m (x3 over 27m)      kubelet, node2.*****.biz
  Killing container with id docker://haproxy-ingress:Container failed liveness probe.. Container will be killed and recreated.
  Normal   Pulled                 26m (x4 over 27m)      kubelet, **
**  Successfully pulled image "quay.io/jcmoraisjr/haproxy-ingress"
  Warning  BackOff                2m42s (x101 over 26m)  kubelet, node2.*****.biz
  Back-off restarting failed container
```

Checking HaProxy Blog documentation, [HaproxyBlog](https://www.haproxy.com/blog/haproxy_ingress_controller_for_kubernetes/), there is a difference between 2 daemonsets manifests, the "hostNetwork: true" field. 

According the first guide we are setting a hostNetwork in daemonset manifest but we don't see the same in HaProxy Blog (they don't set up this). We tried the latest beta too (v0.7-beta.5). 

Other pods in the cluster are communicating fine with the Api Server. 

Where is the problem?

Thanks,

**Comment by jcmoraisjr** [comment] 2019-01-16 14:39
@rendiok Hi, this clearly sounds to me a problem to connect to k8s IP. What if you `curl https://10.3.0.1` from your host, outside any container, or if you change hostNetwork to false? Take the k8s internal IP (`kubectl -n default get ep`) and what if you `curl https://internal-ip:port` from the host? Perhaps you have a problem with service IP used outside any container or a routing problem to the internal k8s IP. Perhaps hostNetwork=false + hostPort isn't an option (you'll loose the source IP from clients) so you can use a certificate based authentication (see `--kubeconfig`) and use the public IP of your apiserver.

**Comment by rendiok** [comment] 2019-01-29 08:14
Hey jcmoraisjr!

Sorry for the delay and thanks for your help.

Finally yes, I changed "hostNetwork" to false and now it's working.

Thanks again!

**Comment by rikatz** [comment] 2020-07-05 20:46
@rendiok Doing some old unclosed issues pass here, as the problem is solved can you please close this one?

Thanks!

**Closed** 2020-07-05 21:22 UTC
