### ISSUE TITLE
Missing frontend when upgrading from v0.11.1 to v011.2

### ISSUE THREAD

**Issue by mhyllander** [jcmoraisjr/haproxy-ingress#733] opened 2021-02-05 16:50 UTC
When I upgraded from v0.11.1 to v0.11.2, I got a strange problem where I'm missing a frontend map entry for one of my ingresses.

For the ingress+service, a frontend+backend should be defined (as before).

Not sure if I can give exact steps, since I don't know what is wrong. I have haproxy-ingress installed in the core namespace, and it is picking up on Ingress resources in several other namespaces. But for one Ingress in the monitoring namespace, when I upgrade to v0.11.2, I only see the backend in /etc/haproxy/haproxy.cfg, but no entries for the host in the /etc/haproxy/maps/\_front\_* files. The backend has configured the correct IP:port to the pod.

If I downgrade to v0.11.1 the Ingress works again and I can access the service.

I should also mention that I am using cert-manager to generate a LetsEncrypt certificate. That seems to be working, because the certificate gets generated and haproxy-ingress has picked up on it and added it to /etc/haproxy/maps/\_front_bind\_crt.list.

**Environment information**

HAProxy Ingress version: `v0.11.2`

Command-line options:

```
--configmap=core/internal-ingress-haproxy --ingress-class=internal --sort-backends --default-backend-service=core/internal-ingress-haproxy-default-backend --default-ssl-certificate=core/hivestreaming.com-tls --reload-strategy=reusesocket
```

Global options:

```
  backend-server-slots-increment: "100"
  config-frontend: |
    #-------------------------------------------------------------
    capture request header Host len 40
    capture request header User-Agent len 100
    capture request header X-Forwarded-For len 100
    #-------------------------------------------------------------
  dns-hold-obsolete: 30s
  dns-hold-valid: 30s
  dns-resolvers: kubernetes=10.128.0.10
  dynamic-scaling: "true"
  forwardfor: update
  healthz-port: "10253"
  http-log-format: '%ci:%cp\ [%t]\ %ft\ %b/%s\ %sslv\ %sslc\ %Tq/%Tw/%Tc/%Tr/%Tt\
    %ST\ %B\ %U\ %CC\ %CS\ %tsc\ %ac/%fc/%bc/%sc/%rc\ %sq/%bq\ %hr\ %hs\ %{+Q}r'
  max-connections: "500000"
  prometheus-port: "9101"
  ssl-ciphers: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
  ssl-dh-param: core/dh-param
  ssl-options: no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets
  stats-port: "1936"
  syslog-endpoint: localhost:514
  tcp-log-format: '%ci:%cp\ [%t]\ %ft\ %b/%s\ %sslv\ %sslc\ %Tw/%Tc/%Tt\ %B\ %U\ %ts\
    %ac/%fc/%bc/%sc/%rc\ %sq/%bq'
  timeout-stop: 1h
```

Ingress objects:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: internal-letsencrypt-prod
    kubernetes.io/ingress.class: internal
    meta.helm.sh/release-name: monitoring
    meta.helm.sh/release-namespace: monitoring
  labels:
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 7.3.7
    helm.sh/chart: grafana-6.1.17
  name: monitoring-grafana
  namespace: monitoring
spec:
  rules:
  - host: grafana.dev.hivestreaming.net
    http:
      paths:
      - backend:
          serviceName: monitoring-grafana
          servicePort: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - grafana.dev.hivestreaming.net
    secretName: grafana.dev.hivestreaming.net
```

**Comment by jcmoraisjr** [comment] 2021-02-05 17:09
Hi, can you provide a list of hostnames (no problem if obfuscated, provided that the same sources generates the same targets), paths (needs the real ones) and pathType of your cluster? If you have a big amount of them, provide at least all paths and path types of a hostname where the config is right and another one that the config isn't right.

**Comment by mhyllander** [comment] 2021-02-08 11:19
Hi, I assume you mean hostnames, paths and pathTypes used in Ingress resources? While I was collecting this information, I noticed that some ingresses have pathType `Prefix` and some have `ImplementationSpecific`, so I experimented a little.

When I set the pathType of the monitoring-grafana ingress above to `Prefix`, it is picked up correctly and configured by the controller. Change back and it's removed again.

On the other hand, there are two other Ingresses in the same namespace, one with pathType `ImplementationSpecific` and one with `Prefix`, and those are working:

```yaml
  - host: monitoring.dev.hivestreaming.net
    http:
      paths:
      - backend:
          serviceName: monitoring-kube-prometheus-alertmanager
          servicePort: 9093
        path: /prometheus-alert-manager
        pathType: ImplementationSpecific
```

```yaml
  - host: monitoring.dev.hivestreaming.net
    http:
      paths:
      - backend:
          serviceName: monitoring-prometheus-thanos-querier
          servicePort: 9090
        path: /prometheus
        pathType: Prefix
```

On a whim, I tested to change the pathType of the second one to `ImplementationSpecific` to see what would happen, expecting the monitoring.dev.hivestreaming.net frontend to disappear. And it did, but at the same time, the grafana.dev.hivestreaming.net frontend was added (still ImplementationSpecific)!.

To summarize:

With the original configuration I have pasted above,
* grafana.dev.hivestreaming.net/ is missing
* monitoring.dev.hivestreaming.net/prometheus-alert-manager is added to _front_https_host__begin_01.map
* monitoring.dev.hivestreaming.net/prometheus is added to _front_https_host__prefix.map

When I set the pathType of monitoring.dev.hivestreaming.net/prometheus and monitoring.dev.hivestreaming.net/prometheus-alert-manager to `ImplementationSpecific`,
* grafana.dev.hivestreaming.net/ is added to _front_https_host__begin.map
* monitoring.dev.hivestreaming.net/prometheus-alert-manager is missing
* monitoring.dev.hivestreaming.net/prometheus is missing

When I set the pathType of monitoring.dev.hivestreaming.net/prometheus and monitoring.dev.hivestreaming.net/prometheus-alert-manager to `Prefix`,
* grafana.dev.hivestreaming.net/ is missing
* monitoring.dev.hivestreaming.net/prometheus-alert-manager is added to _front_https_host__prefix.map
* monitoring.dev.hivestreaming.net/prometheus is added to _front_https_host__prefix.map

When I set the pathType to `Prefix` on all three ingresses,
* grafana.dev.hivestreaming.net/ is added to _front_https_host__prefix.map
* monitoring.dev.hivestreaming.net/prometheus-alert-manager is added to _front_https_host__prefix.map
* monitoring.dev.hivestreaming.net/prometheus is added to _front_https_host__prefix.map

**Comment by jcmoraisjr** [comment] 2021-02-09 01:51
Thank you for the detailed description, however I couldn't reproduce any of them, neither in 1.18 nor 1.20 kubernetes versions. I did also a review in the code, it's still unclear to me how this behavior is even possible, since ingress data are grouped by hostnames and changes to one of them shouldn't mess data of another one.

Maybe it's feasible to you to generate and deploy a custom image, if so I'd create a patch with more debug info showing what the controller is doing. This would be very helpful. Or maybe you can or prefer to provide a subset of your ingress resources that reproduces the issue - so I hope we can debug it locally. Hostnames can be obfuscated.

Other than that I'll continue the investigation in the code, improve unit tests trying to find some new corner cases. I'll update here if I find anything useful.

**Comment by mhyllander** [comment] 2021-02-10 20:44
Hi, thanks for looking into this. I think it would be hard for me to set up an environment where I can experiment to find a subset of ingresses. I'm open to try with a custom image, I think that would be easiest.

**Comment by jcmoraisjr** [comment] 2021-02-11 01:26
Thank you also for reporting this issue. See attached a patch over v0.11.2 that adds some verbosity. There will be a lot of new log on every cluster update, and the log will represent the new state.

[v0.11.3-r1.patch.zip](https://github.com/jcmoraisjr/haproxy-ingress/files/5962633/v0.11.3-r1.patch.zip)

I've also created this temporary image `quay.io/jcmoraisjr/h:v0.11.3-r1`. It's exactly the same v0.11.2 with the patch above, built however on my local env instead of travis. You can send the logs in pvt (same user under gmail) if you prefer in order to avoid disclosure some sensitive data.

**Comment by mhyllander** [comment] 2021-02-15 23:29
@jcmoraisjr I have sent you a log file on gmail, with details of what I changed and when.

**Comment by jcmoraisjr** [comment] 2021-02-16 00:44
Hi, thank you so much for the time spent in this issue and the provided logs. I've just tagged another image `quay.io/jcmoraisjr/h:v0.11.3-r2` with the following patch on top of r1:

```diff
diff --git a/pkg/haproxy/types/maps.go b/pkg/haproxy/types/maps.go
index b2fed17d..4ac1f512 100644
--- a/pkg/haproxy/types/maps.go
+++ b/pkg/haproxy/types/maps.go
@@ -273,7 +273,7 @@ func (hm *HostsMap) HasHost() bool {
 func (mf *hostsMapMatchFile) shrink() {
 	e := mf.entries
 	l := len(e)
-	for i := range e {
+	for i := l - 1; i >= 0; i-- {
 		if e[i]._elem != nil {
 			glog.Infof("--- shrink %s%s", e[i].hostname, e[i].path)
 			l--
```

Please confirm if this solves the problem you found on your env. If so I'll tag a new release shortly, otherwise please send again these same logs - changing an ingress just once and producing an invalid config is enough.

**Comment by mhyllander** [comment] 2021-02-16 08:33
I tested this morning and this seems to have solved the problem! I changed the pathType back and forth on the three ingresses, and the map file contents remained stable and the same after each change. And I could access the services. Thank you for the quick work, and happy to be able to help!

**Comment by jcmoraisjr** [comment] 2021-02-16 17:16
Awesome! I've just created the pr that should be merged shortly. I'll notify here as soon as v0.11 is tagged with the fix.

**Comment by mhyllander** [comment] 2021-02-17 10:43
Great! When you do release, I also submitted a PR with some additions to haproxy-ingress chart, which would also be nice to have: https://github.com/haproxy-ingress/charts/pull/11

**Comment by jcmoraisjr** [comment] 2021-02-18 01:13
Everything should be working now with v0.11.3 which was just released. Helm chart also updated, hope I didn't any mess cherry picking the changes. Closing now and thanks again for reporting this and helping us diagnosing what was wrong.

**Closed by jcmoraisjr** 2021-02-18 01:13 UTC
Labels: kind/bug

**Comment by mhyllander** [comment] 2021-02-18 08:11
Great, thanks! I will try it out today. Also thought I would mention that with 0.11.1 that we have currently deployed, I had not yet configured ouath2_proxy correctly. When I did that yesterday, I discovered that it did not work. I then tried it with the patched `quay.io/jcmoraisjr/h:v0.11.3-r2`, and thenn it worked. So I have great hopes that 0.11.3 will solve all problems. 😃
