### ISSUE TITLE
secure-verify-ca-secret with secret in other namespace than haproxy-ingress

### ISSUE THREAD

**Issue by nielspardon** [jcmoraisjr/haproxy-ingress#29] opened 2017-07-26 13:50 UTC
I was trying to set up an ingress with the annotations `secure-backends: "true"` and a `secure-verify-ca-secret`.

My `haproxy-ingress` is running in the `default` namespace while my ingress and services in running in a separate namespace.

I created the ca secret as a generic secret with exactly one element called `ca.crt` and the ca certificate in PEM format.

From the logs of the `haproxy-ingress` pod I see that it detects the annotation but is unable to fetch the secret from the other namespace.

Any idea what might be wrong? (running kubernetes 1.6.6 through Rancher)

```
kubectl create secret generic -n other ca-secret --from-file=ca.crt
```

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  namespace: other
  annotations:
    ingress.kubernetes.io/secure-backends: "true"
    ingress.kubernetes.io/secure-verify-ca-secret: "ca-secret"
spec:
  rules:
  - host: example.com
  tls:
  - hosts:
    - example.com
    secretName: example-secret
  backend:
    serviceName: app-service
    servicePort: 443
```

```
I0726 12:29:24.702877       7 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"other", Name:"app-ingress", UID:"xxx", APIVersion:"extensions", ResourceVersion:"8277915", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress other/app-ingress
E0726 12:29:24.800131       7 annotations.go:112] error parsing secure upstream: error obtaining certificate: secret other/ca-secret does not exist
I0726 12:29:24.800150       7 leaderelection.go:203] attempting to acquire leader lease...
I0726 12:29:24.800477       7 backend_ssl.go:63] adding secret other/ca-secret to the local store
I0726 12:29:24.800744       7 controller.go:1022] ssl certificate "other/example-secret" does not exist in local store
I0726 12:29:24.801265       7 backend_ssl.go:63] adding secret other/example-secret to the local store
I0726 12:29:24.825600       7 controller.go:421] ingress backend successfully reloaded...
```

**Comment by jcmoraisjr** [comment] 2017-07-26 15:33
This is a known issue from the core implementation from the ingress repo, which is reused by HAProxy Ingress as a dependency: secret is acquired before being added to the store. Next release should solve this.

Anyway this fetch will be tried again and should work. Please check if your `haproxy.cfg` has the `verify required` configuration on the secured backend after the last reload, otherwise I'll try to reproduce here with kube 1.6.6.

**Comment by jcmoraisjr** [comment] 2017-09-09 20:23
One more note: your secret has been found, the message in the log is just saying that ingress was looking for the secret within the secret store before the secret has being stored there. The config should be working after "adding secret other/..." message.

Closing this, just update this same issue if you still have any problem.

**Closed by jcmoraisjr** 2017-09-09 20:23 UTC
Labels: question

**Comment by fortuneFelix** [comment] 2017-11-08 10:51
Hello,

I love using this ha-proxy ingress controller.
I do come across the same issue when using two-way SSL or specifying the TLS secret, that I can see in the logs that it complains first that the secret couldn't be found, then it updates the config and then the secret is getting loaded, this then leads to the ha-proxy not listening for the ingress/domain.

If I trigger another ingress config change then everything works fine, because the secret is already in the local store.

I assume this has been improved in version 0.4?

Thanks for maintaining this project and the awesome work!

- Felix

**Comment by jcmoraisjr** [comment] 2017-11-08 17:56
Yep, secret updating had some issues on ingress-core, used as a dependency
on this controller. This specific issue was fixed, some others appeared but
now all of them are gone at least on my environments and tests.

Thanks for the feedback =)
