### ISSUE TITLE
Setting weights by backend server individually

### ISSUE THREAD

**Issue by mcortinas** [jcmoraisjr/haproxy-ingress#442] opened 2019-11-08 15:19 UTC
Hello, 
I'm trying to set weights for each backend server in deployment objects such as Appscode Voyager using annotations without lucky, in fact, i'm using haproxy-agent and the haproxy-ingress controller. 

:-1:  The main issue is if I add a sidecar in my application PODs (1 POD with 2 container) sending to the haproxy-agent the weights using ASCII percentage, sometimes the initial value is 0 and the result always will be 0 for this server backend :-1:
`/ # echo "get weight XXX_8080/srv001" | socat stdio unix-connect:/var/run/haproxy-stats.sock 
1 (initial 0)
`

:-1: Furthermore if i send some percentatge it's in an infinite loop, due the ingress controller seems set the weight. it returns some value in one liner:
`/ # echo "set X_8080/srv002 255" | socat stdio unix-connect:/var/run/haproxy-stats.sock; echo "get weight X_8080/srv002" | socat stdio unix-connect:/var/run/haproxy-stats.sock
255 (initial 0)`

If I get it in other command anything is setting to "0".... (ingres-controller ???)
`
/ # echo "get weight X_8080/srv002" | socat stdio unix-connect:/var/run/haproxy-stats.sock
0 (initial 0)
`

I opened a suggestion haproxy community in order to add the feature to set the weights WITHOUT a percentatge using haproxy-agent in https://github.com/haproxy/haproxy/issues/360  

docu link:
- [haproxy doc](http://cbonte.github.io/haproxy-dconv/1.8/configuration.html#5.2-agent-check)
- [ingress doc](https://github.com/jcmoraisjr/haproxy-ingress/blob/aee678a3d995742a859efa7c1442cbb07ef93c28/docs/content/en/docs/configuration/keys.md#agent-check)

The main issue is the initial value is alweays 0 and haproxy-agent works like

> n ASCII representation of a positive integer percentage, e.g. "75%".
  Values in this format will set the weight proportional to the initial
  weight of a server as configured when haproxy starts.

**Could your add-in deployment objects some annotation in the same way Appscode Voyagerlet as set the initial weight value??(https://github.com/appscode/voyager/blob/master/docs/guides/ingress/http/blue-green-deployment.md)**
Example: 

```
apiVersion: extensions/v1beta1
kind: Deployment
spec:
  template:
    metadata:
      annotations:
            <prefix>/initial-backend-weight: "90"```

**Comment by jcmoraisjr** [comment] 2019-11-09 00:29
Hi, I can confirm this misbehaviour, planning to fix before the next v0.8 beta tag.

Just for the record: which version are you using? Is this behaviour happening only on dynamically scaled replicas - added without needing to reload haproxy? Using blue/green deployment or drain support?

**Comment by mcortinas** [comment] 2019-11-09 15:19
Sure!
Finally, I learned blue-green using blue-green-mode in pod mode to cover my requirements. :+1: 
I used version "v0.8-beta.4".
Let me share my annotations
```apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: poc6
  annotations:
    ingress.kubernetes.io/check: "enabled"
    ingress.kubernetes.io/forwarded-for: "enabled"
    #forwarded-for: "update" Only on v0.9 and above. haproxy should preserve any X-Forwarded-For header, if provided, updating
    ingress.kubernetes.io/forwarded-for: "add"
    ingress.kubernetes.io/load-balance: "roundrobin"
    ingress.kubernetes.io/affinity: "cookie"
    ingress.kubernetes.io/session-cookie-name: "INGRESSID"
    ingress.kubernetes.io/session-cookie-dynamic: "true"
    ingress.kubernetes.io/session-cookie-strategy: "insert"
    ingress.kubernetes.io/session-cookie-shared: "false"
    ingress.kubernetes.io/drain-support: "true"
    ingress.kubernetes.io/agent-check-port: "8081"
    ingress.kubernetes.io/agent-check: "true"
    ingress.kubernetes.io/agent-check-interval: "3s"
    ingress.kubernetes.io/backend-check-interval: "2s"
    ingress.kubernetes.io/balance-algorithm: "roundrobin"
    ingress.kubernetes.io/dynamic-scaling: "true"
    ingress.kubernetes.io/slots-min-free: "10" 
```

Let me ask you, when do you plan to deliver v0.8 will be ready for production?

**Comment by jcmoraisjr** [comment] 2019-11-09 17:59
Hi, we are using v0.8 since beta.2 in our production cluster, which is fronting hundreds of applications and thousands of containers. Production ready or not is just a matter of what features you do use. The core functionalities - parsing ingress, building config, reloading and dynamically updating haproxy sounds to be very robust. However you can find some issues on combined functionalities we don't use. If you find them, please let me know.

**Comment by jcmoraisjr** [comment] 2019-11-19 00:04
Hi, this should be fixed in beta.5. [Doc](https://haproxy-ingress.github.io/docs/configuration/keys/#agent-check) was also updated. Closing, just update this same issue if you still have any problem.

**Closed by jcmoraisjr** 2019-11-19 00:04 UTC
Labels: bug
