### ISSUE TITLE
http2: no cached connection was available

### ISSUE THREAD

**Issue by Drupi** [jcmoraisjr/haproxy-ingress#467] opened 2019-11-29 14:26 UTC
Hello, 
I'm using the haproxy-ingress on K8S and from time to time the haproxy-ingress get an problem with connection to api-server which stuck our ingress controller. 
sample logs:

```
E1129 04:59:40.748091       7 reflector.go:205] pkg/mod/k8s.io/client-go@v5.0.0+incompatible/tools/cache/reflector.go:99: Failed to list *v1.Endpoints: Get https://172.20.0.1:443/api/v1/endpoints?resourceVersion=0: http2: no cached connection was available
E1129 04:59:40.749053       7 reflector.go:205] pkg/mod/k8s.io/client-go@v5.0.0+incompatible/tools/cache/reflector.go:99: Failed to list *v1.ConfigMap: Get https://172.20.0.1:443/api/v1/configmaps?resourceVersion=0: http2: no cached connection was available
E1129 04:59:40.750024       7 reflector.go:205] pkg/mod/k8s.io/client-go@v5.0.0+incompatible/tools/cache/reflector.go:99: Failed to list *v1.Secret: Get https://172.20.0.1:443/api/v1/secrets?resourceVersion=0: http2: no cached connection was available
E1129 04:59:40.751076       7 reflector.go:205] pkg/mod/k8s.io/client-go@v5.0.0+incompatible/tools/cache/reflector.go:99: Failed to list *v1.Node: Get https://172.20.0.1:443/api/v1/nodes?resourceVersion=0: http2: no cached connection was available
E1129 04:59:40.752138       7 reflector.go:205] pkg/mod/k8s.io/client-go@v5.0.0+incompatible/tools/cache/reflector.go:99: Failed to list *v1.Service: Get https://172.20.0.1:443/api/v1/services?resourceVersion=0: http2: no cached connection was available
E1129 04:59:40.753228       7 reflector.go:205] pkg/mod/k8s.io/client-go@v5.0.0+incompatible/tools/cache/reflector.go:99: Failed to list *v1.Pod: Get https://172.20.0.1:443/api/v1/pods?resourceVersion=0: http2: no cached connection was available
E1129 04:59:40.754297       7 reflector.go:205] pkg/mod/k8s.io/client-go@v5.0.0+incompatible/tools/cache/reflector.go:99: Failed to list *v1beta1.Ingress: Get https://172.20.0.1:443/apis/extensions/v1beta1/ingresses?resourceVersion=0: http2: no cached connection was available
E1129 04:59:41.748319       7 reflector.go:205] pkg/mod/k8s.io/client-go@v5.0.0+incompatible/tools/cache/reflector.go:99: Failed to list *v1.Endpoints: Get https://172.20.0.1:443/api/v1/endpoints?resourceVersion=0: http2: no cached connection was available
```

Do you have some expierience how to fix it ? 

We are on image:  quay.io/jcmoraisjr/haproxy-ingress:v0.9-snapshot.2

**Comment by jcmoraisjr** [comment] 2019-11-29 17:18
Hi, thanks for reporting. I can confirm this behaviour on apiservers with high availability due to go upgrade without upgrading k8s client. Please check if you can reproduce this with snapshot.1. Btw you can copy vendor from release-0.8 and build v0.9 with go1.9.2 which should fix this issue as well.

I'm closing some last-minute v0.8 issues and will take care of this update. Tagging a new snapshot in a week or so.

**Comment by Drupi** [comment] 2019-11-30 21:29
@jcmoraisjr - Thank you for you response - i think we will wait till the official release ;) 
Will try to reproduce it on snapshot.1

**Closed** 2019-12-11 23:30 UTC
Labels: bug

**Comment by jcmoraisjr** [comment] 2019-12-12 00:53
Hi, please let me know if you can reproduce this issue with v0.9-snapshot.3. Thanks!
