### ISSUE TITLE
503 for first backend server in latest and v0.6-beta.1 when dynamic-scaling is true

### ISSUE THREAD

**Issue by swapnil1988** [jcmoraisjr/haproxy-ingress#175] opened 2018-06-12 09:34 UTC
**This issue is observed in latest and v0.6-beta.1, this issue is not observed in v0.5**

Basically when a new ingress resource is added the first server0000 is always disabled and gives a **503 Service Unavailable** error other backend servers (server0001 ...) works fine.

```
######                                                                                                                           
###### Backends                                                                                                                  
######                                                                                                                           
backend abc-svc-8089                                                                                 
    mode http                                                                                                                    
    balance roundrobin                                                                                                           
    server server0000 10.44.0.8:8078 maxconn 1 weight 1 check port 8078 inter 2s  // **gives 503 always**                                               
    server server0001 10.44.0.10:8078 maxconn 1 weight 1 check port 8078 inter 2s // **this works fine**           
    server server0002 127.0.0.1:81 maxconn 1 check disabled inter 2s            
    server server0003 127.0.0.1:81 maxconn 1 check disabled inter 2s            
    server server0004 127.0.0.1:81 maxconn 1 check disabled inter 2s            
    server server0005 127.0.0.1:81 maxconn 1 check disabled inter 2s            
    server server0006 127.0.0.1:81 maxconn 1 check disabled inter 2s            
    server server0007 127.0.0.1:81 maxconn 1 check disabled inter 2s
```

**All endpoints when accessed directly work which means all the endpoints are active**

**Comment by jcmoraisjr** [comment] 2018-06-20 22:29
Hi, how was your test that conclude the first endpoint always give 503?

Give more details about your env, which default ingress configuration you changed, your ingress resource, how you provisioned your k8s, etc. so I can also reproduce.

**Comment by swapnil1988** [comment] 2018-06-25 06:35
Hi @jcmoraisjr, Thanks for the reply.

Below are the details 

**K8s version 1.10.4** is a bare metal install using kubeadm.

**Default Ingress configuration changed**

```
    "dynamic-scaling": "true",
    "max-connections": "5000",
    "syslog-endpoint": "127.0.0.1:5140",
```
"backend-check-interval": "2s", is default and is some how causing the issue. I kind of disabled it by changing the interval to "backend-check-interval": "99999999999999h", and the issue disappeared. 

**Ingress resource:**

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  namespace: app-namespace
  annotations:
    kubernetes.io/ingress.class: "app-name"
    ingress.kubernetes.io/ssl-passthrough: "false"
    ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/rewrite-target: "/"
    ingress.kubernetes.io/maxconn-server: "1" //This is the extra piece which is not supported in v.0.5 
    ingress.kubernetes.io/slots-increment: 20
spec:
  rules:
  - http:
      paths:
      - path: /app-name
        backend:
          serviceName: app-svc
          servicePort: 8089
```

**Comment by dewjam** [comment] 2018-07-05 15:51
@jcmoraisjr @swapnil1988 I have been experiencing this exact same issue.  In short, the HAProxy TCP health-check returns an L4 connection failure, even though you can communicate with the pod via telnet/curl on the appropriate port from the Ingress Controller pod.  Triggering a full reload of the HAProxy config seems to resolve the problem.  And, as mentioned by @swapnil1988 , it only happens on the first pod/server in the list.

I haven't done a great deal of testing, but I assume this is either a misconfiguration in check timeouts vs check interval, or a bug in HAProxy.  I can't see how this could be a bug with the ingress controller code itself.

**Comment by jcmoraisjr** [comment] 2018-07-21 21:56
Hi, beta2 with HAProxy 1.8.12 is out since last weekend. Please check if updating will solve the issue for you.

**Comment by jcmoraisjr** [comment] 2020-10-18 13:27
Thanks for reporting and for the detailed description. #232 fixed a similar issue which should this one. Closing.

**Closed by jcmoraisjr** 2020-10-18 13:27 UTC
