### ISSUE TITLE
Affinity cookie value varies between instances

### ISSUE THREAD

**Issue by dobesv** [jcmoraisjr/haproxy-ingress#113] opened 2018-03-12 13:09 UTC
I am seeing different affinity cookie values for the same backend in different instances of the haproxy controller.  This breaks session affinity if users do not go to the same haproxy instance each time.

One container:

```
    server server0006 100.96.4.10:3000 check port 3000 inter 2s cookie QSDE/osy6aA=
    server server0000 100.96.4.5:3000 check port 3000 inter 2s cookie N9hPNu3uxOg=
    server server0005 100.96.4.6:3000 check port 3000 inter 2s cookie pfOO1OuP3m0=
    server server0004 100.96.4.7:3000 check port 3000 inter 2s cookie JKeNBmwjZ2I=
    server server0001 100.96.60.58:3000 check port 3000 inter 2s cookie B5fM4+zNanw=
    server server0003 100.96.65.45:3000 check port 3000 inter 2s cookie kRuaCn62Dk4=
    server server0002 100.96.65.46:3000 check port 3000 inter 2s cookie 4uc1Y/t2z78=
```

Another:

```
    server server0006 100.96.4.10:3000 check port 3000 inter 2s cookie QSDE/osy6aA=
    server server0002 100.96.4.5:3000 check port 3000 inter 2s cookie 4uc1Y/t2z78=
    server server0005 100.96.4.6:3000 check port 3000 inter 2s cookie pfOO1OuP3m0=
    server server0004 100.96.4.7:3000 check port 3000 inter 2s cookie JKeNBmwjZ2I=
    server server0003 100.96.60.58:3000 check port 3000 inter 2s cookie kRuaCn62Dk4=
    server server0000 100.96.65.45:3000 check port 3000 inter 2s cookie N9hPNu3uxOg=
    server server0001 100.96.65.46:3000 check port 3000 inter 2s cookie B5fM4+zNanw=
```

In order for session affinity to work, the cookie must refer to the same backend each time.

**Comment by jcmoraisjr** [comment] 2018-03-12 15:19
Yep, this is a known issue regarding affinity and dynamic scaling. The problem is that I cannot build a hash based on the endpoint because this might be changed and the HAProxy API doesn't allow me to change this hash, so it's based on the server name.

 `v0.6` will use [dynamic cookie](http://cbonte.github.io/haproxy-dconv/1.8/configuration.html#4.2-cookie), a HAProxy 1.8 feature, which will avoid this and other problem related with persistent sessions. I'm planning to release a snapshot in a few days and this snapshot will fix this problem.

**Comment by jcmoraisjr** [comment] 2018-03-12 15:21
...btw you can avoid this right now removing dynamic scaling, or wait a few more days and use a v0.6 snapshot.

**Comment by dobesv** [comment] 2018-03-12 16:16
It seems like settings the sort-backends option alleviates the problem for the most part.  People can still get bounced between backends if they are added or removed but at least it is consistent between haproxy instances.

**Comment by jcmoraisjr** [comment] 2018-05-14 23:55
Now the snapshot of v0.6 has also dynamic cookies. Their values are built by HAProxy using the backend ip and port, and also a custom key. Closing.

**Closed by jcmoraisjr** 2018-05-14 23:55 UTC
Labels: enhancement
